workflows:
  android_debug:
    name: Android Debug APK
    environment:
      flutter: stable
      java: 17
    cache:
      cache_default_paths: true
    scripts:
      - name: Ensure Android platform exists
        script: |
          if [ ! -d "android" ]; then
            echo "Android folder not found. Creating Flutter platform files..."
            flutter create . --platforms=android
          else
            echo "Android folder found."
          fi
      - name: Fetch dependencies
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - ${CM_EMAIL:-}
        notify:
          success: true
          failure: true